version: '3.8'
services:
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./jupyter/notebooks:/home/jupyteruser/work  # Mount volume for CSV file access
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4g'
  spark-worker:
    image: bitnami/spark:3.4.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./jupyter/notebooks:/home/jupyteruser/work  # Mount volume for CSV file access
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4g'

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  jupyterlab:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyterlab
    volumes:
      - ./jupyter/notebooks:/home/jupyteruser/work
    ports:
      - "8888:8888"
    depends_on:
      - spark-master
      - spark-worker
      - minio
    links:
      - spark-master
      - spark-worker
