version: '3'
services:
  jupyter:
    build: ./jupyterlab
    container_name: jupyter-pyspark
    ports:
      - "8888:8888"  # Exposing Jupyter Lab's default port
    volumes:
      - ./notebooks:/home/jovyan/work  # Mount a local directory for notebooks
    environment:
      - SPARK_MASTER=--master spark://spark-master:7077
    depends_on:
      - spark-master

  spark-master:
    hostname: spark-master
    container_name: spark-master
    image: bitnami/spark:3.4.1
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    hostname: spark-worker-1
    container_name: spark-worker-1
    image: bitnami/spark:3.4.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 5g
      SPARK_MASTER_URL: spark://spark-master:7077

networks:
  default:
    driver: bridge
