FROM patipatc/pyspark-notebook:py3.12_spark_3.4.1

# run jupyter lab
CMD ["jupyter", "lab", "--ip", "0.0.0.0", "--port", "8888", "--NotebookApp.token=''", "--NotebookApp.password=''", "--no-browser", "--allow-root"]